### ISSUE TITLE
Fix lobby concurrency crash

### ISSUE THREAD

**Issue by paulcscharf** [beardgame/td#15]
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
  at at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
  at at System.Collections.Immutable.Requires.Range(Boolean condition, String parameterName, String message)
  at at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
  at at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
  at at Bearded.TD.UI.Controls.LobbyControl.LoadingBlueprintsListSource.CreateItemControlFor(Int32 index)
  at at Bearded.UI.Controls.ListControl.createCellControl(Int32 index, Double top, Double bottom)
  at at Bearded.UI.Controls.ListControl.createCellIfVisible(Int32 index, Double bottom, Double top, Double height)
  at at Bearded.UI.Controls.ListControl.addCellAbove(Int32 index, Double bottom)
  at at Bearded.UI.Controls.ListControl.addCellsUpwards()
  at at Bearded.UI.Controls.ListControl.Reload()
  at at Beard

**Comment by tomrijnbeek** [comment]
I can reproduce this by resizing the lobby screen a lot.
