### ISSUE TITLE
FinishBuildingConstruction command does not find building

### ISSUE THREAD

**Issue by paulcscharf** [beardgame/td#6]
Happened on client. I think the building was destroyed by an enemy while building clientside and not server side? Or maybe I'm imagining it.

```
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bearded.TD.Game.GameState.Find[T](Id`1 id)
   at Bearded.TD.Game.Commands.FinishBuildingConstruction.Serializer.GetCommand(GameInstance game)
   at Bearded.TD.Commands.Serialization.SerializerExtensions.Read[TObject](ICommandSerializer`1 me, NetBufferReader stream, TObject context)
   at Bearded.TD.Game.ClientDataMessageHandler.Handle(NetIncomingMessage msg)
   at Bearded.TD.Networking.NetworkInterface.ConsumeMessages()
   at Bearded.TD.Game.GameRunner.Update(UpdateEventArgs args)
   at Bearded.TD.UI.Controls.GameUI.Update(UpdateEventArgs args)
   at Bearded.TD.UI.UIUpdater.Update(UpdateEventArgs args)
   at Bearded.TD.TheGame.OnUpdate(UpdateEventArgs e)
   at amulware.Graphics.Program.run(Double targetUpdatesPerSecond, Double targetDrawsPerSecond, Double maximumFrameTimeFactor, Boolean dontOverrideFps) in C:\Users\amulware\git\td\libs\awgraphics\src\amulware.Graphics\Window\Program.cs:line 279
   at amulware.Graphics.Program.<>c__DisplayClass22_0.<Run>b__0() in C:\Users\amulware\git\td\libs\awgraphics\src\amulware.Graphics\Window\Program.cs:line 211
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by tomrijnbeek** [comment]
This is actually a problem on the server too. The building is deleted, but since the server only works with references, it just marks a non-existing building as finishes. On the client however, it tries to resolve the reference by ID, which fails.

The solution is to cancel the worker task as part of the building deletion.
